import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const generatePdfReport = async (projectData: any, captureElementId: string) => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  // 1. Header
  pdf.setFillColor(15, 23, 42); // Slate 800
  pdf.rect(0, 0, pageWidth, 30, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('OCC Pulp Mill Sizing - Technical Datasheet', 10, 15);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Generated by OCC Mill Sizer Application', 10, 22);

  // 2. Project Details
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Project Parameters:', 10, 45);
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Project Name: ${projectData.project_name}`, 10, 52);
  pdf.text(`Tier: ${projectData.tier}`, 10, 58);
  pdf.text(`Capacity: ${projectData.target_capacity_adt} ADT/day`, 10, 64);
  pdf.text(`Contamination: Metals ${projectData.contamination.metals}, Plastics ${projectData.contamination.plastics}, Stickies ${projectData.contamination.stickies}, Ash ${projectData.contamination.ash}`, 10, 70);

  // 3. Equipment List Table
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Sized Equipment List:', 10, 85);
  
  let y = 95;
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  pdf.setFillColor(229, 231, 235); // Gray 200
  pdf.rect(10, y-5, pageWidth - 20, 7, 'F');
  pdf.text('Category', 12, y);
  pdf.text('Calculated Size', 80, y);
  pdf.text('OEMs', 130, y);
  
  pdf.setFont('helvetica', 'normal');
  y += 8;
  
  projectData.result.equipment_list.forEach((eq: any) => {
    if (y > pageHeight - 40) {
      pdf.addPage();
      y = 20;
    }
    let sizeStr = eq.calculated_volume_m3 ? `${eq.calculated_volume_m3} m3` : 
                  eq.calculated_area_m2 ? `${eq.calculated_area_m2} m2` : 
                  eq.type || 'N/A';
    let oemStr = eq.recommended_oems ? eq.recommended_oems.map((o: any) => `${o.oem} ${o.model}`).join(', ') : eq.oem || 'N/A';
    
    pdf.text(eq.category, 12, y);
    pdf.text(sizeStr, 80, y);
    pdf.text(oemStr.substring(0, 60), 130, y); // Truncate long strings
    y += 7;
  });

  // 4. Capture PFD Diagram
  y += 10;
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Process Flow Diagram (PFD):', 10, y);
  y += 5;

  const input = document.getElementById(captureElementId);
  if (input) {
    const canvas = await html2canvas(input, { scale: 2, backgroundColor: '#ffffff' });
    const imgData = canvas.toDataURL('image/png');
    
    // Calculate image dimensions to fit page width
    const imgWidth = pageWidth - 20;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    
    // Add new page if PFD doesn't fit
    if (y + imgHeight > pageHeight - 10) {
      pdf.addPage();
      y = 10;
    }
    
    pdf.addImage(imgData, 'PNG', 10, y, imgWidth, imgHeight);
  }

  pdf.save(`${projectData.project_name.replace(/\s/g, '_')}_Datasheet.pdf`);
};
